name: nurse_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  dropdown_button2: ^2.3.9
  url_launcher: ^6.3.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
