name: nurse_app
description: "A new Flutter project."
version: 1.0.2+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  dropdown_button2: ^2.3.9
  url_launcher: ^6.3.0
  http: ^1.2.2
  image_picker: ^1.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  quickalert: ^1.1.0
  flutter_bloc: ^8.1.6
  logger: ^2.4.0
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pinput: ^5.0.0
  carousel_slider: ^5.0.0
  pusher_channels_flutter:
    git:
      url: https://github.com/ArmanKT/pusher-channels-flutter.git
      ref: master
  cached_network_image: ^3.4.1
  onesignal_flutter: ^5.2.5
  dio: ^5.7.0
  auto_size_text: ^3.0.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  expandable_page_view: ^1.0.17
  intrinsic_size_builder: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
