// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUIYmbPNGwlGntz4EPsPI3_5y_qClIvkI',
    appId: '1:700423121842:web:e662a7c166899afe5692ab',
    messagingSenderId: '700423121842',
    projectId: 'alahmadnursecare-f93ff',
    authDomain: 'alahmadnursecare-f93ff.firebaseapp.com',
    storageBucket: 'alahmadnursecare-f93ff.firebasestorage.app',
    measurementId: 'G-MTSGVYTTM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADUsbAjAyxf2lBjzK5zDTySyJxsf8Lov0',
    appId: '1:700423121842:android:293fed7f7eb125b35692ab',
    messagingSenderId: '700423121842',
    projectId: 'alahmadnursecare-f93ff',
    storageBucket: 'alahmadnursecare-f93ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeD267MW3PuLAZ9UnFwwHl9MJfaYlYG1Y',
    appId: '1:700423121842:ios:66a5f71a9d7913515692ab',
    messagingSenderId: '700423121842',
    projectId: 'alahmadnursecare-f93ff',
    storageBucket: 'alahmadnursecare-f93ff.firebasestorage.app',
    iosBundleId: 'com.devzur.nursecare',
  );
}